# Generated by Django 4.2.17 on 2025-02-06 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.CharField(max_length=200)),
                ('taste', models.TextField(help_text='Enter a brief description of the taste', max_length=1000)),
                ('name', models.CharField(help_text='130 Characters for the name of the tea', max_length=130, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='TeaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular tea', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('e', 'Empty'), ('a', 'Available'), ('f', 'Favorite')], default='a', help_text='Tea availability', max_length=1)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a tea type (e.g. green, black etc.)', max_length=200, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='type',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='type_name_case_insensitive_unique', violation_error_message='Type already exists (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='teainstance',
            name='tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.tea'),
        ),
        migrations.AddField(
            model_name='tea',
            name='genre',
            field=models.ManyToManyField(help_text='Select a type for this tea', to='catalog.type'),
        ),
        migrations.AddField(
            model_name='tea',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.shop'),
        ),
    ]
